version: '2.2'
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    command: /bin/bash ./entrypoint.sh
    ports:
     - 1433:1433
    environment:
     - ACCEPT_EULA=Y
     - MSSQL_PID=Standard
     - SA_PASSWORD=Password!
     - MSSQL_AGENT_ENABLED=true
    volumes:
      - dbdata:/var/opt/mssql/data
      - ./scripts/docker-entrypoint.sh:/entrypoint.sh
      - ./scripts/docker-db-init.sh:/db-init.sh
      - ./scripts/docker-db-init.sql:/db-init.sql
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
     - sqlserver
    environment:
      - ADM_INSTALL_MSSQL=true
      - PHP_FPM_INSTALL_MSSQL=true
      - WORKSPACE_INSTALL_MSSQL=true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    restart: always
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5552:5552"

  update-elastic:
    build: UpdateElastic/
    depends_on:
        - rabbitmq

volumes:
  dbdata:
  esdata1:
    driver: local