FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY UpdateElastic/*.csproj ./UpdateElastic/
COPY shared/*.csproj ./shared/

# Copy everything else and build
COPY UpdateElastic/. ./UpdateElastic/
COPY shared/. ./shared/

WORKDIR /app/UpdateElastic
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/UpdateElastic/out .
ENTRYPOINT ["dotnet", "UpdateElastic.dll"]
