FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY API/*.csproj ./API/
COPY Shared/*.csproj ./Shared/
RUN dotnet restore ./API/API.csproj
RUN dotnet restore ./Shared/Shared.csproj

# Copy everything else and build
COPY API/. ./API/
COPY Shared/. ./Shared/

WORKDIR /app/API
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/API/out .
ENTRYPOINT ["dotnet", "API.dll"]