FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY UpdateElastic/*.csproj ./UpdateElastic/
COPY Shared/*.csproj ./Shared/
RUN dotnet restore ./UpdateElastic/UpdateElastic.csproj
RUN dotnet restore ./Shared/Shared.csproj

# Copy everything else and build
COPY UpdateElastic/. ./UpdateElastic/
COPY Shared/. ./Shared/

WORKDIR /app/UpdateElastic
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/UpdateElastic/out .
ENTRYPOINT ["dotnet", "UpdateElastic.dll"]